<?php
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function _arr($max, $a, $b)
{
  $array = [$a, $b];

  while (true) {
    $temp = $b;
    $b = $a + $b;
    $a = $temp;
    if ($b <= $max)
    {
      array_push($array, $b);
    } else
    {
      return $array;
    }
  }
}

$sum = 0;
foreach (_arr(4e6, 1, 2) as $key => $value) {
  if ($value % 2 == 0)
  {
    $sum += $value;
  }
}
echo $sum;
?>
